#Spring.datasource.url=jdbc:mysql://localhost:3306/OA?useUnicode=true&characterEncoding=utf-8&useSSL=false
#Spring.datasource.username=root
#Spring.datasource.password=123456





server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/OA?useUnicode=true&characterEncoding=utf-8&useSSL=false
    name: mmall-learning
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  type-aliases-package: tk.mybatis.springboot.model
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
  - tk.mybatis.springboot.util.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql




